import mongoose from 'mongoose';
const { Schema } = mongoose;

const ReestrSchema = new Schema({
  'Регистрационный номер договора': String,
  Конкурс: String,
  'Вн\u002e код': String,
  'Номер заявки': String,
  Программа: String,
  '№ договора': Number,
  'Признак дог литера': String,
  '№ проекта': String,
  'Дата договора': String,
  'Текущий статус': String,
  'Срок договора, мес.': Number,
  'Дата завершения': String,
  'Название проекта': String,
  'Сумма договора': Number,
  'Начальная сумма договора': Number,
  'Факт финансирования ВСЕГО': Number,
  Мероприятие: String,
  'Тема НИОКР (Тема работ)': String,
  Исполнитель: String,
  ОПФ: String,
  'ИНН исполнителя': String,
  Руководитель: String,
  Регион: String,
  'Факт. адрес': String,
  КБК: String,
  // Куратор: String,
  'Этап 1\n (дата завершения)': String,
  'Этап 2\n (дата завершения)': String,
  'Этап 3\n (дата завершения)': String,
  'Этап 4\n (дата завершения)': String,
  'План 2020 (руб.)': Number,
  'План 2021 (руб.)': Number,
  'План 2022 (руб.)': Number,
  'Факт 2020 (руб.)': Number,
  'Факт 2021 (руб.)': Number,
});
module.exports = mongoose.model('Reestr', ReestrSchema);
